# Generated by Django 4.2.17 on 2024-12-17 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_fixgroups', '0004_fixgroup_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='наименование товара')),
                ('c_date', models.DateField(auto_now_add=True)),
                ('e_date', models.DateTimeField(verbose_name='окончание срока')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_fixgroups.fixgroup')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
