# Generated by Django 4.2.17 on 2024-12-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fixgroups', '0002_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='rank',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Гость'), (1, 'Мерч/Кас'), (2, 'Админ'), (7, 'su')], default=0),
        ),
    ]
