# Generated by Django 4.2.17 on 2024-12-18 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_fixgroups', '0004_fixgroup_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateField(verbose_name='дата ревизии')),
                ('archive', models.BooleanField(default=False, verbose_name='архив')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_fixgroups.fixgroup')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
