# Generated by Django 4.2.17 on 2024-12-18 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_revision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='имя списка')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_revision.revision')),
            ],
        ),
    ]
