# Generated by Django 4.2.17 on 2024-12-19 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_fixgroups', '0004_fixgroup_owner'),
        ('app_revision', '0002_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='имя записи')),
                ('barcode', models.CharField(max_length=32, verbose_name='баркод')),
                ('count', models.PositiveSmallIntegerField(verbose_name='количество')),
                ('note', models.TextField(blank=True, max_length=124, verbose_name='добавить примечание')),
                ('_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_revision.list')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fixgroups.staff')),
            ],
        ),
    ]
